[project]
name = "contact_angle"
readme="README.md"
version="0.0.1"
description = "Contact angle analyser for Molecular Dynamics simulations"
license = {file = "LICENSE"}
requires-python = ">=3.8"

[project.urls]
Source = "https://github.com/andrew-liang-2001/contact_angle"

